server:
  port: 8040
security:
  oauth2:
    client:
      user-authorization-uri:  http://localhost:8030/oauth/authorize
      access-token-uri: http://localhost:8030/oauth/token
    resource:
      user-info-uri: http://localhost:8030/user/me